Layout/MultilineMethodCallIndentation:
  Enabled: false
Lint/Debugger:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
Metrics/PerceivedComplexity:
  Max: 9
Metrics/CyclomaticComplexity:
  Max: 9
